// Minimal tolerant HTML reader for published TimDS artifacts.
//
// The toolkit ships zero runtime dependencies so client repositories can commit
// a resolved lockfile without inheriting a parser tree. Artifact HTML is
// generated by a static site builder, so this reader targets well-formed
// documents and degrades quietly rather than throwing: unknown constructs
// become text, unclosed inline tags are closed at their parent boundary.

const VOID_ELEMENTS = new Set([
  "area", "base", "br", "col", "embed", "hr", "img", "input",
  "link", "meta", "param", "source", "track", "wbr",
]);

const RAW_TEXT_ELEMENTS = new Set(["script", "style", "textarea", "title"]);

// Which still-open elements a newly opened tag implicitly closes. Keyed by the
// tag being opened; the value is the set of open tags it closes. Applied in a
// loop, so `<tr>` arriving inside an open `<td>` closes the cell and then the
// row. Hand-authored source often omits these closing tags.
const CLOSED_BY = {
  p: new Set(["p"]),
  li: new Set(["li", "p"]),
  tr: new Set(["td", "th", "tr"]),
  td: new Set(["td", "th"]),
  th: new Set(["td", "th"]),
  tbody: new Set(["td", "th", "tr", "thead"]),
  tfoot: new Set(["td", "th", "tr", "tbody", "thead"]),
  dt: new Set(["dt", "dd", "p"]),
  dd: new Set(["dt", "dd", "p"]),
  option: new Set(["option"]),
};

// A <p> cannot contain flow content; opening one of these closes it.
const CLOSES_PARAGRAPH = new Set([
  "address", "article", "aside", "blockquote", "div", "dl", "fieldset",
  "figcaption", "figure", "footer", "form", "h1", "h2", "h3", "h4", "h5",
  "h6", "header", "hr", "main", "nav", "ol", "p", "pre", "section", "table", "ul",
]);

const NAMED_ENTITIES = {
  amp: "&", lt: "<", gt: ">", quot: '"', apos: "'", nbsp: "\u00a0",
  hellip: "…", mdash: "—", ndash: "–", rsquo: "’",
  lsquo: "‘", ldquo: "“", rdquo: "”", middot: "·",
  times: "×", deg: "°", le: "≤", ge: "≥", copy: "©",
};

export function decodeEntities(value) {
  return value.replace(/&(#x?[0-9a-fA-F]+|[a-zA-Z][a-zA-Z0-9]*);/g, (match, body) => {
    if (body[0] === "#") {
      const code = body[1] === "x" || body[1] === "X"
        ? Number.parseInt(body.slice(2), 16)
        : Number.parseInt(body.slice(1), 10);
      return Number.isFinite(code) && code > 0 && code <= 0x10ffff ? String.fromCodePoint(code) : match;
    }
    const named = NAMED_ENTITIES[body];
    return named === undefined ? match : named;
  });
}

function parseAttributes(source) {
  const attrs = {};
  const pattern = /([^\s"'=/<>]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'=<>`]+)))?/g;
  let match;
  while ((match = pattern.exec(source))) {
    const name = match[1].toLowerCase();
    if (name === "/") continue;
    const raw = match[2] ?? match[3] ?? match[4] ?? "";
    attrs[name] = decodeEntities(raw);
  }
  return attrs;
}

const element = (tag, attrs) => ({ type: "element", tag, attrs, children: [] });

/**
 * Parse an HTML document into a lightweight tree.
 * Nodes are `{type:"element", tag, attrs, children}` or `{type:"text", value}`.
 */
export function parseHtml(html) {
  const root = element("#root", {});
  const stack = [root];
  const top = () => stack[stack.length - 1];
  const push = (node) => {
    top().children.push(node);
    stack.push(node);
  };
  const addText = (value) => {
    if (!value) return;
    top().children.push({ type: "text", value: decodeEntities(value) });
  };

  const closeTag = (tag) => {
    for (let i = stack.length - 1; i > 0; i -= 1) {
      if (stack[i].tag === tag) {
        stack.length = i;
        return true;
      }
    }
    return false; // stray close tag: ignore
  };

  let index = 0;
  while (index < html.length) {
    const next = html.indexOf("<", index);
    if (next === -1) {
      addText(html.slice(index));
      break;
    }
    addText(html.slice(index, next));

    if (html.startsWith("<!--", next)) {
      const end = html.indexOf("-->", next + 4);
      index = end === -1 ? html.length : end + 3;
      continue;
    }
    if (html.startsWith("<!", next) || html.startsWith("<?", next)) {
      const end = html.indexOf(">", next);
      index = end === -1 ? html.length : end + 1;
      continue;
    }
    if (html.startsWith("</", next)) {
      const end = html.indexOf(">", next);
      if (end === -1) {
        addText(html.slice(next));
        break;
      }
      closeTag(html.slice(next + 2, end).trim().toLowerCase());
      index = end + 1;
      continue;
    }

    const end = findTagEnd(html, next);
    if (end === -1) {
      addText(html.slice(next));
      break;
    }
    const inner = html.slice(next + 1, end);
    const nameMatch = /^([a-zA-Z][^\s/>]*)/.exec(inner);
    if (!nameMatch) {
      addText(html.slice(next, end + 1));
      index = end + 1;
      continue;
    }
    const tag = nameMatch[1].toLowerCase();
    const attrs = parseAttributes(inner.slice(nameMatch[1].length));
    const selfClosing = inner.trimEnd().endsWith("/");

    const closes = CLOSED_BY[tag];
    while (stack.length > 1 && closes?.has(top().tag)) closeTag(top().tag);
    if (top().tag === "p" && CLOSES_PARAGRAPH.has(tag)) closeTag("p");

    if (VOID_ELEMENTS.has(tag) || selfClosing) {
      top().children.push(element(tag, attrs));
      index = end + 1;
      continue;
    }

    if (RAW_TEXT_ELEMENTS.has(tag)) {
      const node = element(tag, attrs);
      top().children.push(node);
      const closer = new RegExp(`</${tag}\\s*>`, "i");
      const rest = html.slice(end + 1);
      const found = closer.exec(rest);
      const body = found ? rest.slice(0, found.index) : rest;
      if (body) node.children.push({ type: "text", value: body });
      index = found ? end + 1 + found.index + found[0].length : html.length;
      continue;
    }

    push(element(tag, attrs));
    index = end + 1;
  }
  return root;
}

/** Index of the `>` that ends a tag, tolerating `>` inside quoted attributes. */
function findTagEnd(html, start) {
  let quote = null;
  for (let i = start + 1; i < html.length; i += 1) {
    const ch = html[i];
    if (quote) {
      if (ch === quote) quote = null;
      continue;
    }
    if (ch === '"' || ch === "'") quote = ch;
    else if (ch === ">") return i;
  }
  return -1;
}

/* ── traversal helpers ──────────────────────────────────────────────────── */

export function* walk(node) {
  for (const child of node.children ?? []) {
    yield child;
    if (child.type === "element") yield* walk(child);
  }
}

export const attr = (node, name) => node?.attrs?.[name];

export const classList = (node) => String(node?.attrs?.class ?? "").split(/\s+/).filter(Boolean);

export const hasClass = (node, name) => classList(node).includes(name);

export const findAll = (node, predicate) => [...walk(node)].filter((n) => n.type === "element" && predicate(n));

export const findOne = (node, predicate) => findAll(node, predicate)[0];

export const byTag = (node, tag) => findAll(node, (n) => n.tag === tag);

export const elementChildren = (node) => (node.children ?? []).filter((c) => c.type === "element");

const NON_CONTENT = new Set(["script", "style", "svg", "noscript", "template", "button", "select"]);

const INLINE_MARKDOWN = {
  strong: "**", b: "**", em: "*", i: "*",
};

/**
 * Visible text for a node. With `markdown: true`, inline emphasis, inline code,
 * and links are preserved as Markdown.
 */
export function textOf(node, { markdown = false, skip = NON_CONTENT } = {}) {
  let out = "";
  const visit = (n) => {
    if (n.type === "text") {
      out += n.value;
      return;
    }
    if (skip.has(n.tag)) return;
    if (!markdown) {
      n.children.forEach(visit);
      return;
    }
    const wrap = INLINE_MARKDOWN[n.tag];
    if (wrap) {
      out += wrap;
      n.children.forEach(visit);
      out += wrap;
      return;
    }
    // Render children, never the node itself: textOf(n) would re-enter this
    // same branch and recurse forever.
    if (n.tag === "code") {
      const inner = n.children.map((child) => textOf(child, { skip })).join("");
      out += `\`${inner.replace(/\s+/g, " ").trim()}\``;
      return;
    }
    if (n.tag === "a") {
      const href = attr(n, "href");
      const label = n.children
        .map((child) => textOf(child, { markdown: true, skip }))
        .join(" ")
        .replace(/\s+/g, " ")
        .trim();
      out += href ? `[${label}](${href})` : label;
      return;
    }
    if (n.tag === "br") {
      out += " ";
      return;
    }
    n.children.forEach(visit);
  };
  visit(node);
  return out.replace(/\s+/g, " ").trim();
}

/** Raw text with newlines preserved — for <pre> content. */
export function rawTextOf(node) {
  let out = "";
  const visit = (n) => {
    if (n.type === "text") out += n.value;
    else if (!NON_CONTENT.has(n.tag)) n.children.forEach(visit);
  };
  visit(node);
  return out.replace(/^\n+|\s+$/g, "");
}

export function slugify(value, fallback = "item") {
  const raw = String(value);
  const reduce = (input) =>
    input
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 48)
      .replace(/-+$/, "");
  // Inline code inside a longer label is noise ("`--color-bg` semantic token"),
  // but a label that is *only* code still has to produce a usable slug.
  return reduce(raw.replace(/`[^`]*`/g, " ")) || reduce(raw.replace(/`/g, " ")) || fallback;
}
