import assert from "node:assert/strict";
import {promises as fs} from "node:fs";
import path from "node:path";
import test from "node:test";
import {videoFixture} from "./video.fixture.mjs";
import {defaultVideoComponentsTemplate, initializeVideoComponents} from "./video.mjs";
import {migrateVideoComponents, planComponentMigration} from "./video-migration.mjs";

test("snapshot inventory consolidates defaults and retains deliberate visual overrides", async () => {
  const stock = await defaultVideoComponentsTemplate();
  const plain = await planComponentMigration(stock);
  assert.equal(plain.status, "shared");
  assert.match(plain.source, /export \{defaultVideoProjectComponents as default\}/u);
  const customized = stock.replace('const badge = vertical ? 76 : 72;', 'const badge = vertical ? 74 : 70;');
  const plan = await planComponentMigration(customized);
  assert.equal(plan.status, "overrides");
  assert.match(plan.source, /Boards: \{"steps": StepsBoard\}/u);
  assert.match(plan.source, /const badge = vertical \? 74 : 70/u);
  assert.doesNotMatch(plan.source, /const CardsBoard:/u);
  assert.doesNotMatch(plan.source, /const SceneView:/u);
  const review = await planComponentMigration(stock.replace('const SceneView:', 'const SceneView /* client scene */:').replace('if (scene.intro) return', 'if (scene.intro && false) return'));
  assert.equal(review.status, "review");
  assert.ok(review.review.some((reason) => reason.includes("custom Scene")));
  assert.equal((await planComponentMigration(`${stock}\nconsole.log("custom side effect");\n`)).status, "review");
});

test("migration previews, preserves brand and publishing policy, saves rollback bytes, and is safe to rerun", async (t) => {
  const workspace = await videoFixture(t);
  await initializeVideoComponents(workspace);
  workspace.manifest.video.components = "video/remotion.tsx";
  const components = path.join(workspace.designSystemRoot, "video", "remotion.tsx");
  const before = await fs.readFile(components, "utf8");
  const contractPath = path.join(workspace.designSystemRoot, "video", "contract.json");
  const contract = JSON.parse(await fs.readFile(contractPath));
  contract.publishing = {targetDefaults: {shortBridge: "Client policy"}};
  await fs.writeFile(contractPath, `${JSON.stringify(contract, null, 2)}\n`);
  await fs.mkdir(path.join(workspace.designSystemRoot, ".timds"), {recursive: true});
  const defaults = path.join(workspace.designSystemRoot, ".timds", "defaults.json");
  await fs.writeFile(defaults, '{"overrides":["publishing.targetDefaults.shortBridge"]}\n');
  const preview = await migrateVideoComponents(workspace);
  assert.equal(preview.status, "shared"); assert.equal(preview.applied, false);
  assert.equal(await fs.readFile(components, "utf8"), before);
  const result = await migrateVideoComponents(workspace, {apply: true});
  assert.equal(result.applied, true);
  assert.equal(await fs.readFile(path.join(result.backup, "components.tsx"), "utf8"), before);
  const after = JSON.parse(await fs.readFile(contractPath));
  const {runtime, ...preserved} = after;
  const {runtime: previousRuntime, ...expected} = contract;
  assert.deepEqual(preserved, expected);
  assert.equal(runtime.testedVersions, undefined, "recognized defaults adopt the shared compatibility policy");
  assert.ok(runtime.features.includes("shared-board-layouts-v1"));
  assert.equal(await fs.readFile(defaults, "utf8"), '{"overrides":["publishing.targetDefaults.shortBridge"]}\n');
  assert.equal((await migrateVideoComponents(workspace, {apply: true})).applied, false);
  assert.equal(await fs.readFile(path.join(result.backup, "components.tsx"), "utf8"), before);
});
